"""처음 실행하거나 저장 파일이 손상됐을 때 사용할 기본 퀴즈 데이터.

주제는 '대한민국의 지역'이다. 행정구역·지리·명소·특산물을 다루므로
누구나 배경지식이 있으면서도 난이도를 쉬움부터 어려움까지 벌릴 수 있다.

자료 구조는 state.json에 저장될 형태와 똑같다.
리스트(list) 안에 딕셔너리(dict)가 들어 있는 모양인데,
 - 리스트는 여러 문제를 '순서대로' 담고
 - 딕셔너리는 한 문제의 항목들을 'question', 'answer' 같은 이름표로 담는다.
JSON도 정확히 같은 모양이라 파이썬 자료를 그대로 저장할 수 있다.

answer 규칙
    choice / ox : choices의 순번(1부터). O/X는 choices가 ["O", "X"]이므로 O=1, X=2.
    short       : 허용 답안 목록. 띄어쓰기와 대소문자는 채점할 때 무시된다.

문제를 만들 때 지킨 것
 - 선택지만 보고 답을 고를 수 있으면 안 된다. 표기 수준을 서로 맞춘다.
   (예: "제주특별자치도" 하나만 정식 명칭이고 나머지가 줄임말이면 답이 드러난다)
 - 정답 번호가 한쪽에 몰리면 찍어서 맞힐 수 있으므로 1~4에 고르게 분산한다.
 - O/X도 O와 X의 개수를 비슷하게 맞춘다.
"""

DEFAULT_QUIZZES = [
    # ---------- 행정구역 ----------
    {
        "id": 1,
        "type": "ox",
        "difficulty": "easy",
        "question": "대한민국의 광역시는 총 7개다.",
        "choices": ["O", "X"],
        "answer": 2,
        "hint": "특별시와 특별자치시는 광역시에 포함되지 않습니다.",
        "explanation": "광역시는 부산·대구·인천·광주·대전·울산 여섯 곳입니다. "
                       "서울은 특별시, 세종은 특별자치시라 광역시가 아닙니다.",
    },
    {
        "id": 2,
        "type": "choice",
        "difficulty": "normal",
        "question": "다음 중 특별자치도로 전환되지 않은 곳은?",
        "choices": ["강원도", "전라북도", "충청북도", "제주도"],
        "answer": 3,
        "hint": "2006년, 2023년, 2024년에 각각 한 곳씩 전환됐습니다.",
        "explanation": "제주는 2006년, 강원은 2023년, 전북은 2024년에 특별자치도가 됐습니다. "
                       "충청북도는 일반 도로 남아 있습니다.",
    },
    {
        "id": 3,
        "type": "choice",
        "difficulty": "easy",
        "question": "다음 중 광역시가 아닌 도시는?",
        "choices": ["울산", "수원", "대전", "광주"],
        "answer": 2,
        "hint": "인구는 100만이 넘지만 소속된 상위 도가 있습니다.",
        "explanation": "수원은 경기도에 속한 특례시입니다. 인구가 100만을 넘어 "
                       "특례시로 지정됐지만 행정구역상 광역시는 아닙니다.",
    },
    {
        "id": 4,
        "type": "ox",
        "difficulty": "normal",
        "question": "세종특별자치시는 충청남도에 속한다.",
        "choices": ["O", "X"],
        "answer": 2,
        "hint": "소속된 상위 도가 있는지 생각해 보세요.",
        "explanation": "세종특별자치시는 2012년 출범한 광역자치단체로 어느 도에도 속하지 않습니다. "
                       "산하에 시·군·구를 두지 않는 단층제입니다.",
    },
    {
        "id": 5,
        "type": "ox",
        "difficulty": "easy",
        "question": "광주광역시는 전라남도에 속해 있다.",
        "choices": ["O", "X"],
        "answer": 2,
        "hint": "광역시는 도와 같은 등급의 자치단체입니다.",
        "explanation": "광주는 1986년 직할시로 승격되며 전라남도에서 분리됐고, "
                       "1995년 광역시로 이름이 바뀌었습니다.",
    },
    {
        "id": 6,
        "type": "choice",
        "difficulty": "normal",
        "question": "대한민국에서 면적이 가장 넓은 광역자치단체는?",
        "choices": ["경기도", "전라남도", "강원특별자치도", "경상북도"],
        "answer": 4,
        "hint": "산이 많은 강원도보다도 넓습니다.",
        "explanation": "경상북도가 약 19,000㎢로 가장 넓고, 강원특별자치도가 약 16,800㎢로 그 다음입니다.",
    },
    {
        "id": 7,
        "type": "short",
        "difficulty": "normal",
        "question": "대한민국에서 인구가 가장 많은 광역자치단체는?",
        "choices": [],
        "answer": ["경기도", "경기"],
        "hint": "서울보다 많습니다.",
        "explanation": "경기도 인구는 약 1,360만 명으로 서울특별시(약 930만 명)보다 많습니다.",
    },
    {
        "id": 8,
        "type": "choice",
        "difficulty": "hard",
        "question": "다음 중 인구가 가장 적은 광역자치단체는?",
        "choices": ["세종특별자치시", "울산광역시", "제주특별자치도", "광주광역시"],
        "answer": 1,
        "hint": "가장 늦게 만들어진 곳입니다.",
        "explanation": "세종특별자치시는 인구 약 39만 명으로 17개 광역자치단체 중 가장 적습니다.",
    },
    {
        "id": 9,
        "type": "ox",
        "difficulty": "hard",
        "question": "대한민국에서 면적이 가장 작은 광역자치단체는 세종특별자치시다.",
        "choices": ["O", "X"],
        "answer": 1,
        "hint": "서울특별시와 비교해 보세요.",
        "explanation": "세종은 약 465㎢로 서울(약 605㎢)이나 광주(약 501㎢)보다도 작습니다.",
    },
    {
        "id": 10,
        "type": "ox",
        "difficulty": "normal",
        "question": "인천광역시는 대한민국에서 두 번째로 인구가 많은 도시다.",
        "choices": ["O", "X"],
        "answer": 2,
        "hint": "남해안에 있는 도시가 더 많습니다.",
        "explanation": "2위는 부산광역시(약 330만 명)이고 인천은 약 300만 명으로 3위입니다.",
    },

    # ---------- 도청 소재지 ----------
    {
        "id": 11,
        "type": "short",
        "difficulty": "hard",
        "question": "전라남도 도청이 있는 군의 이름은?",
        "choices": [],
        "answer": ["무안", "무안군"],
        "hint": "2005년에 광주광역시에서 이전했습니다.",
        "explanation": "전남도청은 2005년 광주광역시에서 무안군 삼향읍 남악신도시로 옮겨 갔습니다. "
                       "광주가 1986년 직할시로 분리된 뒤에도 도청은 한동안 그대로 남아 있었습니다.",
    },
    {
        "id": 12,
        "type": "choice",
        "difficulty": "normal",
        "question": "경상북도청이 있는 도시는?",
        "choices": ["대구", "포항", "안동", "경주"],
        "answer": 3,
        "hint": "2016년에 대구에서 옮겨 갔습니다.",
        "explanation": "경북도청은 2016년 대구광역시에서 안동시 풍천면 도청신도시로 이전했습니다.",
    },
    {
        "id": 13,
        "type": "short",
        "difficulty": "hard",
        "question": "충청남도 도청이 있는 군의 이름은?",
        "choices": [],
        "answer": ["홍성", "홍성군"],
        "hint": "2012년에 대전광역시에서 이전했습니다.",
        "explanation": "충남도청은 2012년 대전에서 홍성군과 예산군에 걸친 내포신도시로 옮겨 갔으며, "
                       "청사 주소는 홍성군입니다.",
    },
    {
        "id": 14,
        "type": "short",
        "difficulty": "normal",
        "question": "경상남도 도청이 있는 도시는?",
        "choices": [],
        "answer": ["창원", "창원시"],
        "hint": "2010년에 마산·진해와 통합된 도시입니다.",
        "explanation": "경남도청은 창원시에 있습니다. 창원은 2010년 마산·진해와 통합해 인구 100만이 넘는 특례시가 됐습니다.",
    },
    {
        "id": 15,
        "type": "short",
        "difficulty": "normal",
        "question": "전북특별자치도 도청이 있는 도시는?",
        "choices": [],
        "answer": ["전주", "전주시"],
        "hint": "비빔밥과 한옥마을로 유명한 도시입니다.",
        "explanation": "전북도청은 전주시 완산구에 있습니다.",
    },
    {
        "id": 16,
        "type": "choice",
        "difficulty": "normal",
        "question": "강원특별자치도 도청이 있는 도시는?",
        "choices": ["원주", "춘천", "강릉", "속초"],
        "answer": 2,
        "hint": "닭갈비와 막국수로 유명한 도시입니다.",
        "explanation": "강원도청은 춘천시에 있습니다. 인구가 가장 많은 도시는 원주지만 도청은 춘천에 있습니다.",
    },

    # ---------- 산·강·섬 ----------
    {
        "id": 17,
        "type": "choice",
        "difficulty": "easy",
        "question": "한라산이 위치한 광역자치단체는?",
        "choices": ["전라남도", "강원특별자치도", "제주특별자치도", "경상남도"],
        "answer": 3,
        "hint": "우리나라에서 가장 높은 산입니다.",
        "explanation": "한라산은 높이 1,947m로 제주도 한가운데에 있으며 남한에서 가장 높은 산입니다.",
    },
    {
        "id": 18,
        "type": "choice",
        "difficulty": "normal",
        "question": "남한에서 두 번째로 높은 산은?",
        "choices": ["설악산", "지리산", "덕유산", "소백산"],
        "answer": 2,
        "hint": "가장 높은 봉우리의 이름은 천왕봉입니다.",
        "explanation": "지리산 천왕봉이 1,915m로 한라산(1,947m) 다음입니다. 설악산은 1,708m입니다.",
    },
    {
        "id": 19,
        "type": "choice",
        "difficulty": "normal",
        "question": "대한민국 최초의 국립공원으로 지정된 산은?",
        "choices": ["설악산", "한라산", "북한산", "지리산"],
        "answer": 4,
        "hint": "1967년에 지정됐습니다.",
        "explanation": "지리산은 1967년 대한민국 제1호 국립공원으로 지정됐습니다.",
    },
    {
        "id": 20,
        "type": "ox",
        "difficulty": "hard",
        "question": "지리산 국립공원은 전라남도, 전라북도, 경상남도 세 곳에 걸쳐 있다.",
        "choices": ["O", "X"],
        "answer": 1,
        "hint": "국립공원 중 면적이 가장 넓습니다.",
        "explanation": "지리산은 전남 구례, 전북 남원, 경남 함양·산청·하동에 걸쳐 있는 우리나라 최대 규모의 산악형 국립공원입니다.",
    },
    {
        "id": 21,
        "type": "choice",
        "difficulty": "normal",
        "question": "남한에서 가장 긴 강은?",
        "choices": ["낙동강", "한강", "금강", "영산강"],
        "answer": 1,
        "hint": "영남 지방을 남북으로 가로지릅니다.",
        "explanation": "낙동강은 약 510km로 남한에서 가장 깁니다. 한강은 약 494km입니다.",
    },
    {
        "id": 22,
        "type": "ox",
        "difficulty": "easy",
        "question": "제주도는 대한민국에서 가장 큰 섬이다.",
        "choices": ["O", "X"],
        "answer": 1,
        "hint": "면적이 약 1,850㎢입니다.",
        "explanation": "제주도는 약 1,850㎢로 대한민국에서 가장 큰 섬입니다.",
    },
    {
        "id": 23,
        "type": "ox",
        "difficulty": "hard",
        "question": "대한민국에서 두 번째로 큰 섬은 거제도다.",
        "choices": ["O", "X"],
        "answer": 1,
        "hint": "조선소로 유명한 섬입니다.",
        "explanation": "거제도는 약 380㎢로 제주도 다음으로 큽니다. 다리로 육지와 이어져 있습니다.",
    },
    {
        "id": 24,
        "type": "choice",
        "difficulty": "normal",
        "question": "거제도가 속한 광역자치단체는?",
        "choices": ["전라남도", "경상남도", "부산광역시", "경상북도"],
        "answer": 2,
        "hint": "부산과 가깝지만 부산은 아닙니다.",
        "explanation": "거제시는 경상남도에 속하며, 거가대교로 부산과 이어져 있습니다.",
    },
    {
        "id": 25,
        "type": "ox",
        "difficulty": "normal",
        "question": "독도는 경상북도 울릉군에 속한다.",
        "choices": ["O", "X"],
        "answer": 1,
        "hint": "가장 가까운 유인도가 어디인지 생각해 보세요.",
        "explanation": "정확한 주소는 경상북도 울릉군 울릉읍 독도리입니다.",
    },
    {
        "id": 26,
        "type": "ox",
        "difficulty": "normal",
        "question": "울릉도는 강원특별자치도에 속한다.",
        "choices": ["O", "X"],
        "answer": 2,
        "hint": "독도와 같은 군에 속합니다.",
        "explanation": "울릉도는 경상북도 울릉군입니다. 강원도 동해안과 가까워 보이지만 행정구역은 경상북도입니다.",
    },
    {
        "id": 27,
        "type": "short",
        "difficulty": "normal",
        "question": "국토 최남단에 있는 섬의 이름은?",
        "choices": [],
        "answer": ["마라도"],
        "hint": "제주도 남쪽에 있는 작은 섬입니다.",
        "explanation": "마라도는 제주특별자치도 서귀포시 대정읍에 속한 국토 최남단 섬입니다.",
    },
    {
        "id": 28,
        "type": "short",
        "difficulty": "hard",
        "question": "서해 최북단에 있으며 인천광역시 옹진군에 속한 섬은?",
        "choices": [],
        "answer": ["백령도"],
        "hint": "북한 황해도와 매우 가깝습니다.",
        "explanation": "백령도는 인천 옹진군에 속하며 인천항에서 배로 네 시간 넘게 걸립니다.",
    },
    {
        "id": 29,
        "type": "ox",
        "difficulty": "normal",
        "question": "강화도는 인천광역시에 속한다.",
        "choices": ["O", "X"],
        "answer": 1,
        "hint": "1995년에 경기도에서 편입됐습니다.",
        "explanation": "강화군은 1995년 경기도에서 인천광역시로 편입됐습니다.",
    },
    {
        "id": 30,
        "type": "choice",
        "difficulty": "hard",
        "question": "다음 중 섬이 가장 많은 광역자치단체는?",
        "choices": ["인천광역시", "전라남도", "경상남도", "충청남도"],
        "answer": 2,
        "hint": "다도해라는 이름이 붙은 해상국립공원이 있는 곳입니다.",
        "explanation": "전라남도에는 2,000개가 넘는 섬이 있어 우리나라 섬의 60% 이상을 차지합니다.",
    },

    # ---------- 명소·유산 ----------
    {
        "id": 31,
        "type": "choice",
        "difficulty": "easy",
        "question": "불국사와 석굴암이 있는 도시는?",
        "choices": ["안동", "공주", "부여", "경주"],
        "answer": 4,
        "hint": "신라의 수도였던 곳입니다.",
        "explanation": "경상북도 경주시에 있으며 1995년 유네스코 세계유산으로 등재됐습니다.",
    },
    {
        "id": 32,
        "type": "choice",
        "difficulty": "easy",
        "question": "안동 하회마을이 있는 도는?",
        "choices": ["충청북도", "경상북도", "전라북도", "경상남도"],
        "answer": 2,
        "hint": "낙동강이 마을을 휘감아 도는 모습에서 이름이 붙었습니다.",
        "explanation": "경상북도 안동시 풍천면에 있으며 2010년 유네스코 세계유산으로 등재됐습니다.",
    },
    {
        "id": 33,
        "type": "choice",
        "difficulty": "easy",
        "question": "수원 화성이 있는 광역자치단체는?",
        "choices": ["충청남도", "강원특별자치도", "경기도", "경상북도"],
        "answer": 3,
        "hint": "조선 정조가 쌓은 성입니다.",
        "explanation": "경기도 수원시에 있으며 1997년 유네스코 세계유산으로 등재됐습니다.",
    },
    {
        "id": 34,
        "type": "choice",
        "difficulty": "normal",
        "question": "남한산성이 있는 광역자치단체는?",
        "choices": ["충청북도", "강원특별자치도", "서울특별시", "경기도"],
        "answer": 4,
        "hint": "서울과 맞닿은 도시에 있습니다.",
        "explanation": "경기도 광주시에 있으며 2014년 유네스코 세계유산으로 등재됐습니다.",
    },
    {
        "id": 35,
        "type": "choice",
        "difficulty": "hard",
        "question": "해인사 장경판전이 있는 합천군이 속한 도는?",
        "choices": ["경상북도", "경상남도", "전라북도", "충청북도"],
        "answer": 2,
        "hint": "팔만대장경을 보관하고 있는 절입니다.",
        "explanation": "해인사는 경상남도 합천군 가야산에 있으며 장경판전은 1995년 세계유산으로 등재됐습니다.",
    },
    {
        "id": 36,
        "type": "ox",
        "difficulty": "hard",
        "question": "백제역사유적지구는 충청남도에만 분포한다.",
        "choices": ["O", "X"],
        "answer": 2,
        "hint": "백제의 마지막 시기에 중요했던 또 다른 도시를 떠올려 보세요.",
        "explanation": "공주·부여(충남)뿐 아니라 익산(전북)의 왕궁리 유적과 미륵사지도 함께 등재됐습니다.",
    },
    {
        "id": 37,
        "type": "short",
        "difficulty": "easy",
        "question": "첨성대와 대릉원이 있는 경상북도의 도시는?",
        "choices": [],
        "answer": ["경주", "경주시"],
        "hint": "신라 천년의 수도였습니다.",
        "explanation": "경주는 신라의 수도였던 도시로 도시 전체가 유적지에 가깝습니다.",
    },
    {
        "id": 38,
        "type": "choice",
        "difficulty": "hard",
        "question": "유네스코 세계유산 '한국의 갯벌'에 포함된 신안군이 속한 도는?",
        "choices": ["충청남도", "전라북도", "전라남도", "경기도"],
        "answer": 3,
        "hint": "섬이 가장 많은 도이기도 합니다.",
        "explanation": "2021년 등재된 '한국의 갯벌'은 서천(충남)·고창(전북)·신안(전남)·보성순천(전남) 네 곳입니다.",
    },

    # ---------- 특산물·축제 ----------
    {
        "id": 39,
        "type": "choice",
        "difficulty": "normal",
        "question": "보성 녹차밭으로 유명한 보성군이 속한 도는?",
        "choices": ["경상남도", "충청남도", "전라북도", "전라남도"],
        "answer": 4,
        "hint": "남해안에 접한 도입니다.",
        "explanation": "보성군은 전라남도에 속하며 국내 최대 녹차 산지입니다.",
    },
    {
        "id": 40,
        "type": "choice",
        "difficulty": "normal",
        "question": "인삼으로 유명한 금산군이 속한 도는?",
        "choices": ["충청북도", "전라북도", "충청남도", "경상북도"],
        "answer": 3,
        "hint": "대전광역시와 맞닿아 있습니다.",
        "explanation": "금산군은 충청남도에 속하며 국내 최대 인삼 유통지입니다.",
    },
    {
        "id": 41,
        "type": "short",
        "difficulty": "normal",
        "question": "대게로 유명한 영덕군이 속한 도는?",
        "choices": [],
        "answer": ["경상북도", "경북"],
        "hint": "동해안에 접한 도입니다.",
        "explanation": "영덕군은 경상북도 동해안에 있으며 영덕대게로 유명합니다.",
    },
    {
        "id": 42,
        "type": "choice",
        "difficulty": "normal",
        "question": "쌀로 유명한 이천시가 속한 광역자치단체는?",
        "choices": ["충청북도", "강원특별자치도", "전라북도", "경기도"],
        "answer": 4,
        "hint": "도자기 축제로도 알려진 도시입니다.",
        "explanation": "이천시는 경기도에 속하며 임금에게 진상하던 쌀로 유명합니다.",
    },
    {
        "id": 43,
        "type": "choice",
        "difficulty": "normal",
        "question": "머드축제가 열리는 보령시가 속한 도는?",
        "choices": ["충청남도", "전라남도", "경상남도", "강원특별자치도"],
        "answer": 1,
        "hint": "서해안에 접한 도입니다.",
        "explanation": "보령시는 충청남도 서해안에 있으며 대천해수욕장에서 머드축제가 열립니다.",
    },
    {
        "id": 44,
        "type": "choice",
        "difficulty": "normal",
        "question": "산천어축제가 열리는 화천군이 속한 광역자치단체는?",
        "choices": ["경기도", "강원특별자치도", "충청북도", "경상북도"],
        "answer": 2,
        "hint": "겨울에 얼음낚시로 유명한 곳입니다.",
        "explanation": "화천군은 강원특별자치도 북부에 있으며 겨울 산천어축제로 널리 알려져 있습니다.",
    },
    {
        "id": 45,
        "type": "choice",
        "difficulty": "hard",
        "question": "벚꽃으로 유명한 진해 군항제가 열리는 도시는?",
        "choices": ["진주", "통영", "김해", "창원"],
        "answer": 4,
        "hint": "2010년에 진해를 통합한 도시입니다.",
        "explanation": "진해는 2010년 마산과 함께 창원시로 통합돼, 현재 행정구역상 창원시 진해구입니다.",
    },
    {
        "id": 46,
        "type": "choice",
        "difficulty": "normal",
        "question": "유네스코 인류무형문화유산에 등재된 단오제가 열리는 도시는?",
        "choices": ["강릉", "안동", "진주", "남원"],
        "answer": 1,
        "hint": "강원특별자치도 동해안의 도시입니다.",
        "explanation": "강릉단오제는 2005년 유네스코 인류무형문화유산으로 등재됐습니다.",
    },
    {
        "id": 47,
        "type": "choice",
        "difficulty": "easy",
        "question": "닭갈비와 막국수로 유명한 춘천시가 속한 광역자치단체는?",
        "choices": ["강원특별자치도", "충청북도", "경기도", "경상북도"],
        "answer": 1,
        "hint": "소양강댐이 있는 도시입니다.",
        "explanation": "춘천시는 강원특별자치도의 도청 소재지입니다.",
    },
    {
        "id": 48,
        "type": "short",
        "difficulty": "easy",
        "question": "비빔밥과 한옥마을로 유명한 전주시가 속한 광역자치단체는?",
        "choices": [],
        "answer": ["전북특별자치도", "전라북도", "전북"],
        "hint": "2024년에 특별자치도가 됐습니다.",
        "explanation": "전주시는 전북특별자치도의 도청 소재지입니다. 2024년 전라북도가 전북특별자치도로 바뀌었습니다.",
    },

    # ---------- 교통 ----------
    {
        "id": 49,
        "type": "choice",
        "difficulty": "easy",
        "question": "인천국제공항이 자리한 섬은?",
        "choices": ["영종도", "강화도", "백령도", "덕적도"],
        "answer": 1,
        "hint": "인천 앞바다의 섬으로 다리와 공항철도로 이어져 있습니다.",
        "explanation": "인천국제공항은 인천광역시 중구 영종도에 있습니다.",
    },
    {
        "id": 50,
        "type": "ox",
        "difficulty": "hard",
        "question": "제주국제공항은 서귀포시에 있다.",
        "choices": ["O", "X"],
        "answer": 2,
        "hint": "제주도는 시가 두 개뿐입니다.",
        "explanation": "제주국제공항은 제주시에 있습니다. 서귀포시는 한라산 남쪽입니다.",
    },
]

# 첫 실행이나 파일 복구 시 사용할 최고 점수. 아직 아무도 풀지 않았으므로 0.
DEFAULT_BEST_SCORE = 0
